Repository canonical-web-and-design/certification.ubuntu.com, pull requests merged in 2019-09, with the labels that each got.

#54 Support /models endpoint
  templates/models.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#57 Add more output when black linter fails
  package.json
Labels: Review: Code +1

#59 Support make url
  templates/models.html
  webapp/api.py
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#62 Enable talisker request metrics
  webapp/app.py
Labels: Review: Code needed, Review: QA needed

#64 Add raven dependency
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#65 Change verbiage on desktop landing page
  templates/desktop/index.html
Labels: Review: Code +1, Review: QA +1

#66 Swap to gevent workers
  entrypoint
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#67 Use only 1 worker
  entrypoint
Labels: Review: Code +1
